services:
  banking-app-server:
    container_name: banking-app-server
    restart: unless-stopped
    build:
      context: ../src/server/
      dockerfile: docker/Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001"
    volumes:
      - ./src/server:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm run prisma:pull && npm start
  banking-app-client:
    container_name: banking-app-client
    restart: unless-stopped
    build:
      context: ../src/client/
      dockerfile: docker/Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3002:3002"
    volumes:
      - ./src/client:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm start"
