name: run-docker-compose

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" > .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_IP=${{ secrets.DB_IP }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_SCHEMA=${{ secrets.DB_SCHEMA }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "DATABASE_URL=postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_IP }}:5432/${{ secrets.DB_NAME }}?schema=${{ secrets.DB_SCHEMA }}" >> .env
          cat .env

      - name: Run Docker Compose
        run: docker compose -f ./docker/docker-compose.yml up -d --force-recreate --build